# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------
# Generated by AI (UnitTest MCP)

import builtins
import sys
from unittest.mock import MagicMock

import pytest
from azure.cli.core.azclierror import CLIInternalError

import azext_connectedk8s
import azext_connectedk8s._command_handlers as handlers
import azext_connectedk8s._constants as consts


def test_invoke_delegates_to_custom_command(monkeypatch):
    custom = MagicMock()
    custom.create_connectedk8s.return_value = "result"
    monkeypatch.setitem(sys.modules, "azext_connectedk8s.custom", custom)
    monkeypatch.setattr(azext_connectedk8s, "custom", custom, raising=False)

    result = handlers._invoke("create_connectedk8s", "cmd", name="cluster")

    assert result == "result"
    custom.create_connectedk8s.assert_called_once_with("cmd", name="cluster")


def test_invoke_reports_missing_module_to_user_and_telemetry(monkeypatch):
    missing_module = "missing_connectedk8s_dependency"
    real_import = builtins.__import__

    def fail_custom_import(name, *args, **kwargs):
        if name == "azext_connectedk8s":
            raise ModuleNotFoundError(
                f"No module named '{missing_module}'", name=missing_module
            )
        return real_import(name, *args, **kwargs)

    telemetry = MagicMock()
    monkeypatch.delitem(sys.modules, "azext_connectedk8s.custom", raising=False)
    monkeypatch.setattr(builtins, "__import__", fail_custom_import)
    monkeypatch.setattr(handlers, "telemetry", telemetry)

    with pytest.raises(CLIInternalError) as raised:
        handlers._invoke("create_connectedk8s")

    assert missing_module in str(raised.value)
    properties = telemetry.add_extension_event.call_args.args[1]
    assert properties[consts.Telemetry_Error_Missing_Module_Key] == missing_module
    assert telemetry.set_exception.call_args.kwargs["exception"].name == missing_module
